### ISSUE TITLE
Influxdb Error

### ISSUE THREAD

**Issue by SametBasturkk** [openchia/pool#19]
`(venv) malta2125:~/pool# sudo CHIA_ROOT="~/.chia/mainnet" ./venv/bin/python -m pool
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/pool/pool/__main__.py", line 3, in <module>
    main()
  File "/root/pool/pool/pool_server.py", line 373, in main
    asyncio.run(start_pool_server(pool_config_path=args.config))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/pool/pool/pool_server.py", line 275, in start_pool_server
    server = PoolServer(pool_config_path, config, constants, pool_store)
  File "/root/pool/pool/pool_server.py", line 75, in __init__
    self.pool = Pool(config, pool_config, constants, pool_store)
  File "/root/pool/pool/pool.py", line 105, in __init__
    self.store_ts = InfluxdbStore(pool_config)
  File "/root/pool/pool/store/influxdb_store.py", line 26, in __init__
    self.bucket = self.pool_config['influxdb'].get('bucket', 'openchia')
KeyError: 'influxdb'`

This is the error what I get. what should I do for fix?

**Comment by william-gr** [comment]
You need influx in the config file

**Comment by SametBasturkk** [comment]
> You need influx in the config file

self.pool_config = pool_config

Where you are getting this config? I should hardcode inside the py? I didn't find it in .py files for config location
