### ISSUE TITLE
error when start pool

### ISSUE THREAD

**Issue by terrybok** [openchia/pool#23]
hello,
I just did a fresh install. I can't figure out why I got this error...

`Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/pool/pool/__main__.py", line 3, in <module>
    main()
  File "/home/ubuntu/pool/pool/pool_server.py", line 367, in main
    asyncio.run(start_pool_server(pool_config_path=args.config))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/pool/pool/pool_server.py", line 255, in start_pool_server
    server = PoolServer(pool_config_path)
  File "/home/ubuntu/pool/pool/pool_server.py", line 62, in __init__
    self.pool = Pool(pool_config)
  File "/home/ubuntu/pool/pool/pool.py", line 242, in __init__
    for node in pool_config['nodes']:
KeyError: 'nodes'`

thank you for your help

**Comment by william-gr** [comment]
This is a configuration issue.
We offer the source code, not support.

PRs will be welcomed.
